name: SpritesChat
version: '1.0.0'
main: com.kury.spriteschat.SpritesChatPlugin
api-version: '1.21'
folia-supported: true
authors:
  - Kury
description: Minecraft Chat Icon Sprites and Minecraft-Heads plugin for Folia 1.21.11
softdepend: [PlaceholderAPI, TAB, LuckPerms]

commands:
  sprites:
    description: Lệnh chính của SpritesChat
    aliases: [sprite, schat, sc]
    permission: spriteschat.use

permissions:
  spriteschat.use:
    description: Cho phép sử dụng icon sprites cơ bản trong chat
    default: true
  spriteschat.use.heads:
    description: Cho phép sử dụng icon player head trong chat
    default: true
  spriteschat.admin:
    description: Quyền quản trị và cấu hình plugin SpritesChat
    default: op
